-- Migration: Add checklist_items and claims tables for Readiness module (Phase 5)

-- 1. Create checklist_items table
CREATE TABLE IF NOT EXISTS public.checklist_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_key text UNIQUE NOT NULL,
    item_text text NOT NULL,
    detail_text text NOT NULL,
    weight numeric NOT NULL,
    display_order integer NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for checklist_items
ALTER TABLE public.checklist_items ENABLE ROW LEVEL SECURITY;

-- Allow read access for checklist_items to everyone (authenticated and anonymous)
CREATE POLICY "Allow read access for checklist_items to all"
ON public.checklist_items FOR SELECT
USING (true);


-- 2. Create claims table
CREATE TABLE IF NOT EXISTS public.claims (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    checklist_state jsonb NOT NULL DEFAULT '{}'::jsonb,
    readiness_score numeric NOT NULL DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for claims
ALTER TABLE public.claims ENABLE ROW LEVEL SECURITY;

-- Policies for claims: per-user pattern (same as bills and scheme_matches)
CREATE POLICY "Users can read their own claims"
ON public.claims FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own claims"
ON public.claims FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Users can update their own claims"
ON public.claims FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Allow anonymous inserts (while auth is suspended)
CREATE POLICY "Allow anonymous inserts for claims"
ON public.claims FOR INSERT
TO anon
WITH CHECK (user_id IS NULL);

-- Allow anonymous updates (while auth is suspended — match on null user_id via id)
CREATE POLICY "Allow anonymous updates for claims"
ON public.claims FOR UPDATE
TO anon
USING (user_id IS NULL);


-- ==========================================================
-- SEED DATA: checklist_items
-- Weights: 25 + 25 + 20 + 20 + 10 = 100
-- ==========================================================

INSERT INTO public.checklist_items (item_key, item_text, detail_text, weight, display_order) VALUES
(
  'diag_match',
  'Diagnosis code matches discharge summary',
  'The ICD-10 diagnosis code on your insurance claim form must exactly match the diagnosis documented in the hospital discharge summary. A mismatch — even a minor one — is the single most common reason insurers flag a claim for manual audit or outright rejection. Cross-check both documents before submission.',
  25,
  1
),
(
  'proc_match',
  'Procedure code matches billed treatment',
  'The CPT/procedure code billed by the hospital must correspond precisely to the surgical or medical procedure actually performed and documented in your operation notes. Upcoding (billing a more complex procedure) or mismatches between the OT notes and the bill will trigger claim denial.',
  25,
  2
),
(
  'docs_complete',
  'All discharge documents attached',
  'A complete claim packet must include: signed discharge summary, itemized hospital bill, all original payment receipts, prescription copies for pharmacy claims, and lab or imaging reports supporting the diagnosis. Missing even one document delays settlement by 15–30 days on average.',
  20,
  3
),
(
  'preauth',
  'Pre-authorization obtained (if required)',
  'For planned admissions at network hospitals, insurers require a pre-authorization code from their Third Party Administrator (TPA) before or on the day of admission. Claims for planned procedures without pre-auth are routinely downgraded from cashless to reimbursement — or rejected entirely. Emergency admissions must notify the TPA within 24 hours.',
  20,
  4
),
(
  'policy_active',
  'Policy active & premium paid to date',
  'Confirm that your health insurance policy is currently active, has not lapsed due to a missed premium, and the sum insured has not been exhausted for the policy year. Insurers validate policy status at the time of claim adjudication — a policy that was active at admission but lapses during hospital stay can still create complications.',
  10,
  5
);
