-- Migration: Add scheme_rules, generic_swaps, and scheme_matches tables for Matcher module

-- 1. Create scheme_rules table
CREATE TABLE IF NOT EXISTS public.scheme_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diagnosis text NOT NULL,
    income_bracket text CHECK (income_bracket IN ('low', 'mid')) NOT NULL,
    scheme_name text NOT NULL,
    coverage_amount numeric NOT NULL,
    note text NOT NULL,
    state text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for scheme_rules
ALTER TABLE public.scheme_rules ENABLE ROW LEVEL SECURITY;

-- Allow read access for scheme_rules to everyone (authenticated and anonymous)
CREATE POLICY "Allow read access for scheme_rules to all" 
ON public.scheme_rules FOR SELECT 
USING (true);


-- 2. Create generic_swaps table
CREATE TABLE IF NOT EXISTS public.generic_swaps (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diagnosis text NOT NULL,
    branded_name text NOT NULL,
    branded_price numeric NOT NULL,
    generic_name text NOT NULL,
    generic_price numeric NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for generic_swaps
ALTER TABLE public.generic_swaps ENABLE ROW LEVEL SECURITY;

-- Allow read access for generic_swaps to everyone (authenticated and anonymous)
CREATE POLICY "Allow read access for generic_swaps to all" 
ON public.generic_swaps FOR SELECT 
USING (true);


-- 3. Create scheme_matches table
CREATE TABLE IF NOT EXISTS public.scheme_matches (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    diagnosis text NOT NULL,
    income_bracket text NOT NULL,
    state text NOT NULL,
    matched_scheme text,
    coverage_amount numeric,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for scheme_matches
ALTER TABLE public.scheme_matches ENABLE ROW LEVEL SECURITY;

-- Policies for scheme_matches: per-user pattern as bills
CREATE POLICY "Users can read their own scheme matches" 
ON public.scheme_matches FOR SELECT 
TO authenticated 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own scheme matches" 
ON public.scheme_matches FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Allow anonymous inserts for scheme matches"
ON public.scheme_matches FOR INSERT
TO anon
WITH CHECK (user_id IS NULL);


-- ==========================================================
-- SEED DATA: scheme_rules (4 diagnoses x 2 income brackets: low, mid)
-- NOTE: 'high' income bracket is intentionally NOT seeded.
-- ==========================================================

-- CARDIAC
INSERT INTO public.scheme_rules (diagnosis, income_bracket, scheme_name, coverage_amount, note, state) VALUES
('cardiac', 'low', 'Ayushman Bharat PM-JAY (National)', 500000, '100% cashless coverage for cardiology & cardiothoracic surgeries including angioplasty, stenting, and bypass (CABG) across all empanelled hospitals nationwide.', NULL),
('cardiac', 'mid', 'State Universal Health Assurance & Trust Care', 200000, 'Subsidized packages for cardiac diagnostics and interventions available at empanelled public and charitable trust hospitals.', NULL),
('cardiac', 'low', 'Mahatma Jyotirao Phule Jan Arogya Yojana (MJPJAY)', 500000, 'Cashless cardiac interventions, valve replacements, and pacemaker implantations at network hospitals across Maharashtra.', 'Maharashtra'),
('cardiac', 'mid', 'MJPJAY Universal Health Scheme', 500000, 'Universal health protection for all Maharashtra ration-card holder families for secondary and tertiary cardiac procedures.', 'Maharashtra'),
('cardiac', 'low', 'Chief Minister''s Comprehensive Health Insurance Scheme (CMCHIS)', 500000, 'Full cashless cardiac procedures and ICU packages at empanelled government and private healthcare centres in Tamil Nadu.', 'Tamil Nadu'),
('cardiac', 'low', 'Ayushman Bharat - Arogya Karnataka (AB-ArK)', 500000, 'Cashless treatment for complex cardiovascular conditions and surgical interventions in Karnataka.', 'Karnataka'),
('cardiac', 'low', 'Dr. YSR Aarogyasri Health Scheme', 500000, 'End-to-end cashless tertiary cardiac care and post-operative financial support in Andhra Pradesh.', 'Andhra Pradesh');

-- MATERNITY
INSERT INTO public.scheme_rules (diagnosis, income_bracket, scheme_name, coverage_amount, note, state) VALUES
('maternity', 'low', 'Janani Shishu Suraksha Karyakram (JSSK) & PM-JAY', 50000, 'Completely free and cashless normal/C-section delivery, drugs, diagnostics, and diet, plus direct cash transfer via PMMVY.', NULL),
('maternity', 'mid', 'Pradhan Mantri Matru Vandana Yojana (PMMVY)', 6000, 'Direct Benefit Transfer (DBT) wage-loss compensation and maternal nutrition assistance for institutional delivery.', NULL),
('maternity', 'low', 'MJPJAY Maternity & Neonatal Package', 100000, 'Comprehensive high-risk pregnancy, C-section delivery, and sick newborn care coverage across Maharashtra network hospitals.', 'Maharashtra'),
('maternity', 'low', 'Dr. Muthulakshmi Reddy Maternity Benefit Scheme', 18000, 'Financial assistance and maternal nutrition kit support for pregnant mothers in Tamil Nadu.', 'Tamil Nadu');

-- DIABETES
INSERT INTO public.scheme_rules (diagnosis, income_bracket, scheme_name, coverage_amount, note, state) VALUES
('diabetes', 'low', 'National Programme for Prevention of NCDs (NP-NCD) & PM-JAY', 500000, 'Free regular insulin and HbA1c screening at health & wellness centres; secondary/tertiary diabetic hospitalization covered under PM-JAY.', NULL),
('diabetes', 'mid', 'National NCD Care & Jan Aushadhi Scheme', 25000, 'Free essential anti-diabetic medications (Metformin, Glimepiride) and subsidized lab testing at district hospitals and Jan Aushadhi Kendras.', NULL),
('diabetes', 'low', 'Delhi Arogya Kosh & Free Diagnostic Scheme', 50000, 'Free essential diabetic medicines, insulin vials, and 450+ lab tests at Mohalla Clinics and Delhi government facilities.', 'Delhi');

-- ORTHOPEDIC
INSERT INTO public.scheme_rules (diagnosis, income_bracket, scheme_name, coverage_amount, note, state) VALUES
('orthopedic', 'low', 'Ayushman Bharat PM-JAY Joint Replacement & Trauma', 500000, '100% cashless hip/knee replacement, fracture fixation, and trauma care with NPPA-capped implant pricing.', NULL),
('orthopedic', 'mid', 'State Orthopedic Care & NPPA Ceiling Rate Assurance', 150000, 'Capped knee and hip implant pricing under National Pharmaceutical Pricing Authority (NPPA) directives with subsidized trust hospital surgery rates.', NULL),
('orthopedic', 'low', 'MJPJAY Polytrauma & Joint Replacement Package', 250000, 'Cashless orthopedic joint replacement and trauma surgery coverage in Maharashtra.', 'Maharashtra'),
('orthopedic', 'low', 'CMCHIS Orthopedic Reconstruction Scheme', 500000, 'Cashless orthopedic surgeries, spinal instrumentation, and joint reconstruction in Tamil Nadu.', 'Tamil Nadu');


-- ==========================================================
-- SEED DATA: generic_swaps (4 diagnoses)
-- ==========================================================

-- CARDIAC
INSERT INTO public.generic_swaps (diagnosis, branded_name, branded_price, generic_name, generic_price) VALUES
('cardiac', 'Atorva 20mg (Atorvastatin) - 10 Tablets', 240.00, 'Jan Aushadhi Atorvastatin 20mg - 10 Tablets', 35.00),
('cardiac', 'Telma 40 (Telmisartan 40mg) - 15 Tablets', 210.00, 'Jan Aushadhi Telmisartan 40mg - 10 Tablets', 28.00),
('cardiac', 'Clopilet 75 (Clopidogrel 75mg) - 10 Tablets', 145.00, 'Jan Aushadhi Clopidogrel 75mg - 10 Tablets', 22.00);

-- MATERNITY
INSERT INTO public.generic_swaps (diagnosis, branded_name, branded_price, generic_name, generic_price) VALUES
('maternity', 'Orofer-XT (Ferrous Ascorbate + Folic Acid) - 30 Tabs', 340.00, 'Jan Aushadhi Iron & Folic Acid - 30 Tablets', 45.00),
('maternity', 'Shelcal 500 (Calcium 500mg + Vit D3) - 15 Tablets', 145.00, 'Jan Aushadhi Calcium 500mg + D3 - 10 Tablets', 22.00),
('maternity', 'Folvite 5mg (Folic Acid 5mg) - 30 Tablets', 85.00, 'Jan Aushadhi Folic Acid 5mg - 30 Tablets', 12.00);

-- DIABETES
INSERT INTO public.generic_swaps (diagnosis, branded_name, branded_price, generic_name, generic_price) VALUES
('diabetes', 'Glycomet GP 1 (Metformin 500mg + Glimepiride 1mg) - 15 Tabs', 165.00, 'Jan Aushadhi Metformin 500mg + Glimepiride 1mg - 10 Tabs', 24.00),
('diabetes', 'Januvia 100mg (Sitagliptin) - 7 Tablets', 390.00, 'Jan Aushadhi Sitagliptin 100mg - 10 Tablets', 65.00),
('diabetes', 'Galvus 50mg (Vildagliptin) - 14 Tablets', 280.00, 'Jan Aushadhi Vildagliptin 50mg - 10 Tablets', 52.00);

-- ORTHOPEDIC
INSERT INTO public.generic_swaps (diagnosis, branded_name, branded_price, generic_name, generic_price) VALUES
('orthopedic', 'Zerodol-SP (Aceclofenac + Paracetamol + Serratiopeptidase) - 10 Tabs', 135.00, 'Jan Aushadhi Aceclofenac + Paracetamol + Serratiopeptidase - 10 Tabs', 30.00),
('orthopedic', 'Cartigen 1500 (Glucosamine Sulfate 1500mg) - 15 Tablets', 420.00, 'Jan Aushadhi Glucosamine Sulfate 1500mg - 10 Tablets', 75.00),
('orthopedic', 'Ultra-D3 60K (Cholecalciferol 60,000 IU) - 4 Capsules', 150.00, 'Jan Aushadhi Vitamin D3 60K - 4 Capsules', 25.00);
