-- Enable UUID extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create reference_prices table
CREATE TABLE IF NOT EXISTS public.reference_prices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword text UNIQUE NOT NULL,
    reference_amount numeric NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for reference_prices
ALTER TABLE public.reference_prices ENABLE ROW LEVEL SECURITY;

-- Allow read access to reference_prices for everyone (authenticated and anonymous)
CREATE POLICY "Allow read access for reference_prices to all" 
ON public.reference_prices FOR SELECT 
USING (true);

-- Allow write access to reference_prices for service_role only (automatically handled by Supabase)

-- Create bills table
CREATE TABLE IF NOT EXISTS public.bills (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    total_amount numeric NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for bills
ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;

-- Create policies for bills
CREATE POLICY "Users can read their own bills" 
ON public.bills FOR SELECT 
TO authenticated 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own bills" 
ON public.bills FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own bills" 
ON public.bills FOR UPDATE 
TO authenticated 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own bills" 
ON public.bills FOR DELETE 
TO authenticated 
USING (auth.uid() = user_id);

-- Create bill_line_items table
CREATE TABLE IF NOT EXISTS public.bill_line_items (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    bill_id uuid REFERENCES public.bills(id) ON DELETE CASCADE NOT NULL,
    description text NOT NULL,
    charged_amount numeric NOT NULL,
    reference_amount numeric,
    status text CHECK (status IN ('normal', 'questionable', 'inflated')) NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for bill_line_items
ALTER TABLE public.bill_line_items ENABLE ROW LEVEL SECURITY;

-- Create policies for bill_line_items
CREATE POLICY "Users can read their own bill line items" 
ON public.bill_line_items FOR SELECT 
TO authenticated 
USING (
    EXISTS (
        SELECT 1 FROM public.bills 
        WHERE bills.id = bill_line_items.bill_id 
        AND bills.user_id = auth.uid()
    )
);

CREATE POLICY "Users can insert their own bill line items" 
ON public.bill_line_items FOR INSERT 
TO authenticated 
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.bills 
        WHERE bills.id = bill_line_items.bill_id 
        AND bills.user_id = auth.uid()
    )
);

CREATE POLICY "Users can update their own bill line items" 
ON public.bill_line_items FOR UPDATE 
TO authenticated 
USING (
    EXISTS (
        SELECT 1 FROM public.bills 
        WHERE bills.id = bill_line_items.bill_id 
        AND bills.user_id = auth.uid()
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.bills 
        WHERE bills.id = bill_line_items.bill_id 
        AND bills.user_id = auth.uid()
    )
);

CREATE POLICY "Users can delete their own bill line items" 
ON public.bill_line_items FOR DELETE 
TO authenticated 
USING (
    EXISTS (
        SELECT 1 FROM public.bills 
        WHERE bills.id = bill_line_items.bill_id 
        AND bills.user_id = auth.uid()
    )
);
